### ISSUE TITLE
Legg til kort info om API for FDK, med et par eksempler i f.eks. CURL

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/docs#11]
Forslag til innhold

* Finnes det et API for å hente ut informasjon fra katalogen? 
Felles datakatalog er API-drevet så alt du finner i søketjenesten på https://fellesdatakatalog.brreg.no/ kan også hentes ut via API. Dokumentasjon av API-et er tilgjengelig her: https://github.com/brreg/openAPI/blob/master/specs/fdk.yaml (evt i "raw" form: https://raw.githubusercontent.com/brreg/openAPI/master/specs/fdk.yaml )

Et konkret eksempel på API-et, konkret for et datasett fra Bergen kommune: 
curl -H "Accept: application/ld+json" https://fellesdatakatalog.brreg.no/datasets/9abac698-0332-481f-95a1-bd4a88c58d94 

Generelt finner du dokumentasjon og kildekode for katalogen på github, https://github.com/Informasjonsforvaltning/fdk

**Comment by stigbd** [comment]
Godt forslag. Eg utvider forslaget til å gjelde også for:
- begreps-api, og
- api-api

**Comment by stigbd** [comment]
Denne bør løysast i #3

**Comment by stigbd** [comment]
Løst i #3
