### ISSUE TITLE
Egen side om organiseringa vår av repo o.l. i GitHub

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/docs#133]

**Comment by terjesyl** [comment]
@NilsOveTen Skulle dette ut på github.io? Og er dette issuet duplikat av dette? https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/878

**Comment by NilsOveTen** [comment]
det ser veldig kopi-aktig ut, ja. Men hvis vi skal ha en slik oversikt på github.io så tror jeg det bør være en litt enklere variant, og en mer detaljert variant på sharepoint. Men det er ikke nok til at dette issuet egentlig har livets rett, det kan inkluderes i det andre issuet

**Comment by terjesyl** [comment]
Lukker denne siden dette vil løses av https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1006
