### ISSUE TITLE
Dokumentere vokabularet som brukes for å beskrive API i felles datakatalog

### ISSUE THREAD

**Issue by sskagemo** [Informasjonsforvaltning/docs#20]
Jfr behovet for en implementasjonsguide, for å vise mapping mellom ulike spesifikasjonsformat (OAS, FHIR, RAML etc) og den interne representasjonen. Også relevant for https://github.com/Informasjonsforvaltning/behov/issues/12

**Comment by stigbd** [comment]
Første del av av å tilfredsstille dette behovet vil vere å dokumentere API-katalogens API betre ved å få informasjonsmodellen i APIet spesifsert på ein betre måte. Denne vil då bli presenterte i Felles informasjonsmodell-katalog.
Andre del vil dermed bli å dokumentere relasjonen mellom denne modellen og dei ulike standardene vi støtter. Dette vil vere naturlig å dokumentere her under feks "Standard"-seksjon under API-katalog.

**Comment by stigbd** [comment]
Første del av dette er gjort med å publisere informasjonsmodellen som API-apiet eksponerer til [Informasjonsmodell-katalogen](https://fellesdatakatalog.brreg.no/informationModels/0bac56d8-36ff-45c8-86eb-f0c7db36512d) . Ref https://github.com/brreg/openAPI/commit/c1ad442c6344c968c09abeecda954c3929d265d2

**Comment by KjerstiSteien** [comment]
Utgår, da Dcat-ap-no fungerer som spec for API-beskrivelser nå.
