### ISSUE TITLE
Gjenopprette lenke

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/docs#58]
Lenken til "å opprette en brukerhistorie" på Githubsiden https://informasjonsforvaltning.github.io/behovsprosessen 
peker i dag til en side som ikke finnes (gir en feilmelding) @stigbd

**Comment by KjerstiSteien** [comment]
Lukker denne, da siden om behovsprosessen er fjernet frem til vi har landet en behovsprosess å jobbe etter.
