### ISSUE TITLE
Lenker og eksempler på siden for API-katalog som beskriver API må oppdateres

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/docs#65]
Saken gjelder informasjonen på denne siden: https://informasjonsforvaltning.github.io/felles-datakatalog/api-katalog/api/

- Eksemplene på spørringer må oppdateres med korrekte URL-er
- Lenken under "Oppføring i API-katalogen" må oppdateres
- Lenken under "Lenke direkte til spesifikasjon (openAPI v3)" må oppdateres

**Comment by stigbd** [comment]
Lenka til spesifikasjon skal vere som følger:
https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-dataservice-harvester/master/src/main/resources/specification/fdk-dataservice-harvester.yaml
Merk at denne inneheld feile  verdier i servers.url, men det er eit anna issue: https://github.com/Informasjonsforvaltning/fdk-dataservice-harvester/issues/80

**Comment by KurtStian** [comment]
**Eksempelspørringene som må oppdateres med korrekt URL:**

- [ ] Alle API-er: 
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis" 
**må endres til** 
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices"

- [ ] Et spesifikt API basert på id:
 curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis/<id>" 
 **må endres til**
 curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices/<id>"
 (_her kan man vurdere om man ikke skal legge inn en id i eksemplet i stedet for <id>, slik at eksemplet blir tilsvarende de andre eksemplene_)
 
- [ ] En enkelt søk etter API-er med ordet “barnehage”: 
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis?q=barnehage"
**må endres til** 
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices?q=barnehage"

- [ ] Liste alle API-er der utgiver er Registerenheten i Brønnøysund: 
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis?orgPath=/STAT/912660680/974760673"
**må endres til**
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices?orgPath=/STAT/912660680/974760673"

- [ ] Liste endepunkter til alle API-er som realiserer en gitt tjenestetype: (Merk: “environment” er obligatorisk og må enten vere “test” eller “production”.)
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis/endpoints?serviceType=Kontoopplysninger&environment=production"
**må endres til**
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices/endpoints?serviceType=Kontoopplysninger&environment=production"

- [ ] Liste endepunkter til alle API-er som realiserer en gitt tjenestetype for gitte organisasjonsnummer:
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/apis/endpoints?serviceType=Kontoopplysninger&orgNos=984851006,837884942&environment=production"
**må endres til**
curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/dataservices/endpoints?serviceType=Kontoopplysninger&orgNos=984851006,837884942&environment=production"

**Comment by KjerstiSteien** [comment]
Siden er avpublisert, lukker derfor saken.
