### ISSUE TITLE
Lenker og eksempler på siden for Datasettkatalog som beskriver API må oppdateres

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/docs#66]
Saken gjelder informasjonen på denne siden: https://informasjonsforvaltning.github.io/felles-datakatalog/datasett-katalog/api/

- Eksemplene på spørringer som må oppdateres:

  - [ ] Alle datasett med “paginering”, returnerer første side:
         `curl -H "Accept: application/json" 'https://fellesdatakatalog.digdir.no/api/datasets?page=0'`
          Får feilmelding:
          `curl: (1) Protocol "'https" not supported or disabled in libcurl`
          **spørringen må endres til**
          `curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/datasets?page=0"`
       - Vi må bruke anførselstegn i spørringen (foran og bak URL) for at den skal fungere.

  - [ ] Et spesifikt datasett basert på id:
         `curl -H "Accept: application/json" https://fellesdatakatalog.digdir.no/api/datasets/288aa74c-e3d3-492e-9ede- 
          e71503b3bfd9`
          Får feilmelding:
          `303 See Other`og `Location: https://data.norge.no/api/datasets/288aa74c-e3d3-492e-9ede-e71503b3bfd9`
          **spørringen må endres til**
          `curl -H "Accept: application/json" "https://data.norge.no/api/datasets/288aa74c-e3d3-492e-9ede-e71503b3bfd9"`
      - Begynnelsen av URL-en må endres fra https://fellesdatakatalog.digdir.no* til https://data.norge.no*
      - Vi bør bruke anførselstegn i spørringen (foran og bak URL) slik at den er lik spørringene til de andre katalogene.
      - Vi må vurdere å legge inn en id i eksemplet i stedet for `<id>`, slik at eksemplet blir tilsvarende de andre eksemplene.

  - [ ] En enkelt søk etter datasett med ordet “barnehage”:
         `curl -H "Accept: application/json" https://fellesdatakatalog.digdir.no/api/datasets?q=barnehage`
         **spørringen bør endres til**
         `curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/datasets?q=barnehage"`
      - Vi bør bruke anførselstegn i spørringen (foran og bak URL) da url inneholder parametre og slik at den er lik spørringene til de andre katalogene.

Siden URL-en til Felles datakatalog er endret til data.norge.no bør kanskje URL-en til serveren til API-et også endes fra https://fellesdatakatalog.digdir.no* til https://data.norge.no*? At den ene spørringen for datasett allerede må gå mot den nye adressen er et signal på dette. I så fall må URL til alle spørringene også oppdateres med nye URL til server.

- Lenken under "Oppføring i API-katalogen" må oppdateres
- Lenken under "Lenke direkte til spesifikasjon (openAPI v3)" må oppdateres

**Comment by KjerstiSteien** [comment]
Saken er avpublisert. @KurtStian burde vi lage en sak for å få beskrevet API-ene når rate limiting er satt opp?

**Comment by KurtStian** [comment]
> Saken er avpublisert. @KurtStian burde vi lage en sak for å få beskrevet API-ene når rate limiting er satt opp?

Ja. Alle API-en våre bør ligge i API-katalogen og ha oppdatert yaml-fil med beskrivelse av parameterne. I tillegg kunne det sikkert ha vært lurt å lage eksempel på hvordan parameterne kan brukes for de om ikke er teknikere.
