### ISSUE TITLE
Lenker og eventuelt eksempler på siden for Begrepskatalog som beskriver API må oppdateres

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/docs#67]
Saken gjelder informasjonen på denne siden: https://informasjonsforvaltning.github.io/felles-datakatalog/begrepskatalog/api/

- Alle spørringene fungerer men man bør vurdere om det skal legges til anførselstegn på spørringen:

  - [ ] Tilgang til registreringsløsningens samling av publiserte begreper som SKOS-AP-NO:
         `curl -H "Accept: text/turtle" https://registrering-begrep-api.fellesdatakatalog.digdir.no/collections`
         **spørringen bør endres til** (bruke anførselstegn slik at den er lik de andre spørringene)
         `curl -H "Accept: text/turtle" "https://registrering-begrep-api.fellesdatakatalog.digdir.no/collections"`

  - [ ] Et spesifikt begrep basert på id:
         `"curl -H "Accept: application/json" "https://fellesdatakatalog.digdir.no/api/concepts/<id>"`
       - Vi må vurdere å legge inn en id i eksemplet i stedet for `<id>`, slik at eksemplet blir tilsvarende de andre eksemplene.

Siden URL-en til Felles datakatalog er endret til data.norge.no bør kanskje URL-en til serveren til API-et også endes fra https://fellesdatakatalog.digdir.no* til https://data.norge.no*? I så fall må URL til alle spørringene også oppdateres med nye URL til server.

- Lenken under "Oppføring i API-katalogen" må oppdateres
- Lenken under "Lenke direkte til spesifikasjon (openAPI v3)" må oppdateres

**Comment by KjerstiSteien** [comment]
Siden er avpublisert. Lukker derfor saken. Dersom vi skal ha en side som beskriver API for begrepskatalogen, vil det skrives på nytt. og lenker vil oppdateres.
