### ISSUE TITLE
Lenker og eksempler på siden for Informasjonsmodellkatalog som beskriver API må oppdateres

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/docs#68]
Saken gjelder informasjonen på denne siden: https://informasjonsforvaltning.github.io/felles-datakatalog/informasjonsmodell-katalog/api/

- Eksemplene på spørringer som må oppdateres:

  - [ ] Alle informasjonsmodeller:
        `curl -H "Accept: application/json" https://fellesdatakatalog.digdir.no/api/informationmodels`
        Får feilmelding:
        `"status":404,"error":"Not Found","message":"","path":"/informationmodels"`
       - Vi bør bruke anførselstegn i spørringen (foran og bak URL) slik at den er lik spørringene til de andre katalogene.
       -  I tillegg må det gjøres tekniske endringer da denne spørringen får feilmeldingen: "404 Not Found"

  - [ ] En spesifik informasjonsmodell basert på id:
         `curl -H "Accept: application/json" https://fellesdatakatalog.digdir.no/api/informationmodels/0b37ef1a-408b-4e55-8a44-a0e974033c00`
         Får feilmelding:
         `"status":406,"error":"Not Acceptable","message":"","path":"/informationmodels/0b37ef1a-408b-4e55-8a44-a0e974033c00"`
       - Vi bør bruke anførselstegn i spørringen (foran og bak URL) slik at den er lik spørringene til de andre katalogene.
       - Vi må vurdere å legge inn en id i eksemplet i stedet for `<id>`, slik at eksemplet blir tilsvarende de andre eksemplene.
       - I tillegg må det gjøres tekniske endringer da denne spørringen får feilmeldingen: "406 Not Acceptable"

  - [ ] En enkelt søk etter modeller med ordet “summert”:
        `curl -H "Accept: application/json" https://fellesdatakatalog.digdir.no/api/informationmodels?q=summert`
        Får feilmelding:
        `"status":404,"error":"Not Found","message":"","path":"/informationmodels"`
       - Vi bør bruke anførselstegn i spørringen (foran og bak URL) da url inneholder parametre og slik at den er lik spørringene til de andre katalogene.
       - I tillegg må det gjøres tekniske endringer da denne spørringen får feilmeldingen: "404 Not Found"

Siden URL-en til Felles datakatalog er endret til data.norge.no bør kanskje URL-en til serveren til API-et også endes fra https://fellesdatakatalog.digdir.no* til https://data.norge.no*? I så fall må URL til alle spørringene også oppdateres med nye URL til server.

- "Oppføring i API-katalogen" mangler lenke - dette må legges til
- Lenken under "Lenke direkte til spesifikasjon (openAPI v3)" må oppdateres

**Comment by KjerstiSteien** [comment]
Siden er avpublisert. Hvis vi bestemmer oss for å legge denne siden inn igjen, er oppdatering av lenker en av oppgavene vi vil gjøre i forbindelse med det.
